"""user_product_id real de mercado libre en marketplace_listings

Revision ID: 2ac0d9aaa3de
Revises: 1b82f0f87770
Create Date: 2026-08-29 21:25:32.952908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac0d9aaa3de'
down_revision: Union[str, None] = '1b82f0f87770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('user_product_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'user_product_id')
    # ### end Alembic commands ###
