"""comision real de mercado libre por categoria y tipo de publicacion

Revision ID: 3780b4217d64
Revises: ea44b265af0b
Create Date: 2026-08-29 18:58:24.053165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3780b4217d64'
down_revision: Union[str, None] = 'ea44b265af0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercadolibre_category_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('listing_type_id', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage_fee', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'category_id', 'listing_type_id', 'price', name='uq_ml_category_fee_store_category_listing_type_price')
    )
    op.add_column('channel_cost_settings', sa.Column('listing_type_pref', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('ml_category_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('ml_category_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ml_category_name')
    op.drop_column('products', 'ml_category_id')
    op.drop_column('channel_cost_settings', 'listing_type_pref')
    op.drop_table('mercadolibre_category_fees')
    # ### end Alembic commands ###
