"""gtin_confirmado_ausente en product_variants

Revision ID: 9929e468dc32
Revises: c161a8592520
Create Date: 2026-08-30 16:59:03.150690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9929e468dc32'
down_revision: Union[str, None] = 'c161a8592520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default explícito: filas ya existentes quedan en False ("no
    # sabemos" — nunca se infiere que un producto viejo sin barcode
    # confirmó no tener uno).
    op.add_column('product_variants', sa.Column('gtin_confirmado_ausente', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'gtin_confirmado_ausente')
    # ### end Alembic commands ###
