"""family_name real de mercado libre en marketplace_listings

Revision ID: c161a8592520
Revises: 2ac0d9aaa3de
Create Date: 2026-08-30 13:19:11.473660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c161a8592520'
down_revision: Union[str, None] = '2ac0d9aaa3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_listings', sa.Column('family_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_listings', 'family_name')
    # ### end Alembic commands ###
