"""margen objetivo y minimo por canal en channel_cost_settings

Revision ID: cb9872ee2357
Revises: 9929e468dc32
Create Date: 2026-08-30 17:45:39.053524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9872ee2357'
down_revision: Union[str, None] = '9929e468dc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_cost_settings', sa.Column('target_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('channel_cost_settings', sa.Column('min_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_cost_settings', 'min_margin_pct')
    op.drop_column('channel_cost_settings', 'target_margin_pct')
    # ### end Alembic commands ###
