"""stock reservado para mercado libre

Revision ID: d22fcefcb976
Revises: f978b9e55d66
Create Date: 2026-08-24 16:48:14.701288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22fcefcb976'
down_revision: Union[str, None] = 'f978b9e55d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('marketplace_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'marketplace_stock')
    # ### end Alembic commands ###
