"""nickname y site_id de la cuenta de mercado libre

Revision ID: ea44b265af0b
Revises: 69329a46f845
Create Date: 2026-08-29 16:09:42.515566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea44b265af0b'
down_revision: Union[str, None] = '69329a46f845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_accounts', sa.Column('external_account_nickname', sa.String(length=100), nullable=True))
    op.add_column('marketplace_accounts', sa.Column('external_account_site_id', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_accounts', 'external_account_site_id')
    op.drop_column('marketplace_accounts', 'external_account_nickname')
    # ### end Alembic commands ###
